version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: customer_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  customerservice:
    build: ./customerservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/customer_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - postgres
    ports:
      - "8083:8083"

  invoiceservice:
    build: ./invoiceservice
    ports:
      - "8082:8082"

  orderservice:
    build: ./orderservice
    ports:
      - "8081:8081"

  productservice:
    build: ./productservice
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    name: postgres_data